ALT_INCLUDE_PATH=../include
ALT_BIN_PATH=../bin
ALT_LIB_PATH=../lib
ALT_SRC_PATH=.

ALT_LIB_DEPS=""
ALT_LIBNAME=core

CC=xlc


CFLAGS="-I$(ALT_INCLUDE_PATH) -L$(ALT_LIB_PATH) $(ALT_LIB_DEPS)"

cp $(ALT_SRC_PATH)/*.h $(ALT_INCLUDE_PATH)


lib:
	ALT_FILES=core.c
	CFLAGS="-I$(ALT_INCLUDE_PATH) -L$(ALT_LIB_PATH) $(ALT_LIB_DEPS) -o $(ALT_LIB_PATH)/$(ALT_LIBNAME)"
	$(CC) $(CFLAGS) $(ALT_FILES)

server:
	ALT_FILES=server.c
	BIN_NAME=server
	CFLAGS="-I$(ALT_INCLUDE_PATH) -L$(ALT_LIB_PATH) $(ALT_LIB_DEPS) -o $(ALT_BIN_PATH)/$(BIN_NAME)"
